# Generated by Django 5.0.6 on 2024-08-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingInventoryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('SerialNumber', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
